# Generated by Django 5.0 on 2026-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='job_title',
            new_name='job_role',
        ),
        migrations.RemoveField(
            model_name='libraryseat',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='libraryseat',
            name='section',
        ),
        migrations.AddField(
            model_name='libraryseat',
            name='floor',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='libraryseat',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='job_type',
            field=models.CharField(choices=[('internship', 'Internship'), ('fulltime', 'Full Time')], default='fulltime', max_length=50),
        ),
        migrations.AlterField(
            model_name='placement',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('warden', 'Warden'), ('mess_head', 'Mess Head'), ('librarian', 'Librarian'), ('placement_officer', 'Placement Officer')], default='student', max_length=30),
        ),
    ]
