# Generated by Django 5.0 on 2026-02-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_rename_job_title_placement_job_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
